config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  resources :post_images do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :user, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get 'user/:id/mypage' => 'user#mypage', as: "mypage"
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  validates :user_id, uniqueness: {scope: :post_image_id}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  validates :name, presence: true
  validates :image, presence: true


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    else
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/read_count.rb
class ReadCount < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

 # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed
  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  # 指定したユーザーをフォロー
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/man.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    # redirect_to request.referer
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user)
    # redirect_to request.referer
  end

  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def create
    @room = Room.create(user_id: current_user.id)
    @current_entry = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @another_entry = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to rooms_path(@room)
  end
  
  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      # roomで相手の名前を表示するために記述
      @my_user_id = current_user.id
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def mypage
    @user = current_user
    @post_images = @user.post_images.page(params[:page])
  end

  def index
    @users = User.all
    @my_user = User.find_by(id: current_user)
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id then
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      if @is_room
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/relationships/_follow.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <p class="text-left"><%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-info" %></p>
  <% else %>
    <p class="text-left"><%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-success" %></p>
  <% end %>
<% end %>

app/views/relationships/_followers-count.erb
<%= user.followers.count %>

app/views/relationships/_followings-count.erb
<%= user.followings.count %>

app/views/relationships/create.js.erb
$("#follow-btn_<%= @user.id %>").html("<%= j(render 'relationships/follow', user: @user) %>");
$('#followings-count_<%= @user.id %>').html('フォロー：<%= link_to "#{@user.followings.count}", user_followings_path(@user) %>');
$('#followers-count_<%= @user.id %>').html('フォロワー：<%= link_to "#{@user.followers.count}", user_followers_path(@user) %>');

app/views/relationships/destroy.js.erb
$("#follow-btn_<%= @user.id %>").html("<%= j(render 'relationships/follow', user: @user) %>");
$('#followings-count_<%= @user.id %>').html('フォロー：<%= link_to "#{@user.followings.count}", user_followings_path(@user) %>');
$('#followers-count_<%= @user.id %>').html('フォロワー：<%= link_to "#{@user.followers.count}", user_followers_path(@user) %>');

app/views/relationships/followers.html.erb
<div class="card-list-container py-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h1 class="text-center mb-5 border-bottom border-dark"><%= @user.name %>さんのフォロワー一覧</h1>
      <% if @users.exists? %>
        <% @users.each do |user| %>
          <p class="text-center">
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image(50,50) %>
            <%= user.name %>
          <% end %>
          </p>
        <% end %>
      <% else %>
        <p class="text-center">ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="card-list-container py-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h1 class="text-center mb-5 border-bottom border-dark"><%= @user.name %>さんのフォロー一覧</h1>
      <% if @users.exists? %>
        <% @users.each do |user| %>
          <p class="text-center">
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image(50,50) %>
            <%= user.name %>
          <% end %>
          </p>
        <% end %>
      <% else %>
        <p class="text-center">ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>