config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  resources :post_images do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :user, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get 'user/:id/mypage' => 'user#mypage', as: "mypage"
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  validates :user_id, uniqueness: {scope: :post_image_id}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  validates :name, presence: true
  validates :image, presence: true


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    else
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/read_count.rb
class ReadCount < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

 # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed
  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  # 指定したユーザーをフォロー
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/man.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = Message.new(message_params)
    message.user_id = current_user.id
    if message.save
      redirect_to room_path(message.room)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def message_params
    params.require(:message).permit(:room_id, :message)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def create
    @room = Room.create(user_id: current_user.id)
    @current_entry = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @another_entry = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to rooms_path(@room)
  end
  
  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      # roomで相手の名前を表示するために記述
      @my_user_id = current_user.id
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def mypage
    @user = current_user
    @post_images = @user.post_images.page(params[:page])
  end

  def index
    @users = User.all
    @my_user = User.find_by(id: current_user)
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id then
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      if @is_room
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/rooms/show.html.erb
<div class="card-list-container py-5">
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <% @entries.each do |e| %>
      <% if @my_user_id != e.user.id %>
        <h3 class="text-center my-3 bg-dark text-white p-4"><%= e.user.name %>さんとのメッセージ</h3>
      <% end %>
    <% end %>
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <div class="card-body">
          <% if @my_user_id == m.user.id %>
            <div class="bg-info text-white py-2">
              <div class="row">
                <div class="col-2">
                  <%= image_tag m.user.get_profile_image(80,80), class:"mt-3 rounded-circle"; %>
                </div>
                <div class="col-10">
                  <p class="card-title ">
                    <strong><i class="fa-solid fa-user"></i><span> <%= m.user.name %></span></strong>
                  </p>
                  <p class="card-text"><%= m.message %></p>
                </div>
              </div>
            </div>
          <% else %>
            <div class="text-right">
              <div class="row">
                <div class="col-10">
                  <p class="card-title ">
                    <strong><i class="fa-solid fa-user"></i><span> <%= m.user.name %></span></strong>
                  </p>
                  <p class="card-text"><%= m.message %></p>
                </div>
                <div class="col-2">
                  <%= image_tag m.user.get_profile_image(80,80), class:"mt-3 rounded-circle ml-auto" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row no-gutters mb-5">
  <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
    <h5 class="bg-dark text-white p-4 mb-0 text-center">メッセージ</h5>
    <div class="form-body p-3">
      <%= form_with model: @message do |f| %>
        <%= f.text_field :message, placeholder: "メッセージを入力してください", size: 50, class: "form-control" %>
        <%= f.hidden_field :room_id, value: @room.id %>
        <%= f.submit "書き込む", class: "btn btn-lg btn-block btn-success mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/user/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0 text-center">プロフィール編集</h5>
      <div class="form-body p-4">
        <% if @user.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @user.errors.count %>件のエラーが発生しました
            </h6>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @user do |f| %>
          <div class="input-group mb-3 mt-3">
            <p class="mx-auto mb-4">
            <%= f.label :name, "ユーザーネーム" %>
            <%= f.text_field :name, autofocus: true, class:"form-control" %>
            </p>
            <div class="mx-auto mt-4">
              <%= f.file_field :profile_image, accept: "image/*" %>
            </div>
          </div>
          <%= f.submit '変更を保存', class:"btn btn-lg btn-block btn-info mt-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/index.html.erb
<div class="card-list-container py-5">
  <div class="row my-5">
    <div class="col-6 mx-auto">
      <h1 class="text-center mb-5 border-bottom border-dark">Your</h1>
        <div class="col-12 text-center">
          <div class="row mt-5 py-3 border border-dark">
            <div class="col-6">
              <h3 class="text-center mt-3 mb-2"><%= @my_user.name %></h3>
              <%= link_to user_path(@my_user) do %>
                <p class="text-center mt-2"><%= image_tag @my_user.get_profile_image(100,100) %></p>
              <% end %>
              <p class="text-center"><%= link_to "編集", edit_user_path(@my_user), class: "btn btn-success" %></p>
            </div>
            <div class="col-6">
              <div id="follow-btn_<%= @my_user.id %>">
                <%= render "relationships/follow", user: @my_user %>
              </div>
              <div class="text-left" id="followings-count_<%= @my_user.id %>">
                <p>フォロー：<%= link_to @my_user.followings.count, user_followings_path(@my_user) %></p>
              </div>
              <div class="text-left" id="followers-count_<%= @my_user.id %>">
                <p>フォロワー：<%= link_to @my_user.followers.count, user_followers_path(@my_user) %></p>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6 mx-auto my-5">
      <h1 class="text-center mb-5 border-bottom border-dark">ユーザー一覧</h1>
      <div class="col-12 text-center">
        <% @users.each do |user| %>
          <% if user != current_user %>
            <div class="row mt-5 py-3 border">
              <div class="col-6">
                <h3 class="text-center mt-3 mb-2"><%= user.name %></h3>
                <%= link_to user_path(user) do %>
                  <p class="text-center mt-2"><%= image_tag user.get_profile_image(100,100) %></p>
                <% end %>
              </div>
              <div class="col-6">
                <div id="follow-btn_<%= user.id %>">
                  <%= render "relationships/follow", user: user %>
                </div>
                <div class="text-left" id="followings-count_<%= user.id %>">
                  <p>フォロー：<%= link_to user.followings.count, user_followings_path(user) %></p>
                </div>
                <div class="text-left" id="followers-count_<%= user.id %>">
                  <p>フォロワー：<%= link_to user.followers.count, user_followers_path(user) %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/mypage.html.erb
<div class="card-list-container py-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h1 class="text-center mb-5 border-bottom border-dark">マイページ</h1>
      <div class="row mt-5 py-3 border">
        <div class="col-6">
          <h3 class="text-center mt-3 mb-2">ユーザー名：<%= @user.name %></h3>
          <p class="text-center mt-2"><%= image_tag @user.get_profile_image(100,100) %></p>
          <% if @user == current_user %>
            <p class="text-center"><%= link_to "編集", edit_user_path(@user), class: "btn btn-success" %></p>
          <% end %>
        </div>
        <div class="col-6 pt-5">
          <div id="follow-btn_<%= @user.id %>">
            <%= render "relationships/follow", user: @user %>
          </div>
          <div class="text-left" id="followings-count_<%= @user.id %>">
            <p>フォロー：<%= link_to @user.followings.count, user_followings_path(@user) %></p>
          </div>
          <div class="text-left" id="followers-count_<%= @user.id %>">
            <p>フォロワー：<%= link_to @user.followers.count, user_followers_path(@user) %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-6 mx-auto pt-5">
    <h3 class="text-center border-bottom border-dark mt-5">投稿一覧</h3>
  </div>
  <% @post_images.each do |post_image| %>
    <div class="card w-25 mx-auto mt-4 shadow-lg">
      <%= link_to post_image_path(post_image.id) do %>
        <%= image_tag post_image.get_image(200,200), class:"card-img-top"; %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= image_tag post_image.user.get_profile_image(50,50), class:"mt-3 rounded-circle"; %>
          </div>
          <div class="col-10">
            <p class="card-title">
              <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
                <strong><i class="far fa-flag"></i><span> <%= post_image.name %></span></strong>
              <% end %>
            </p>
            <p class="card-text">説明：<%= post_image.caption %></p>
            <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
            <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="d-flex justify-content-center">
    <div class="mt-5"><%= paginate @post_images %></div>
  </div>
</div>

app/views/user/show.html.erb
<div class="card-list-container py-5">
  <div class="row">
    <div class="col-8 mx-auto">
      <h1 class="text-center mb-5 border-bottom border-dark"><%= @user.name %>さんの情報詳細</h1>
      <div class="row text-center">
        <div class="col-6">
          <h3 class="text-center mt-3 mb-2"><%= @user.name %></h3>
          <p class="text-center mt-2"><%= image_tag @user.get_profile_image(100,100) %></p>
          <% if @user == current_user %>
            <p class="text-center"><%= link_to "編集", edit_user_path(@user), class: "btn btn-success" %></p>
          <% end %>
        </div>
        <div class="col-6">
          <div id="follow-btn_<%= @user.id %>">
            <%= render "relationships/follow", user: @user %>
          </div>
          <div class="text-left" id="followings-count_<%= @user.id %>">
            <p>フォロー：<%= link_to @user.followings.count, user_followings_path(@user) %></p>
          </div>
          <div class="text-left" id="followers-count_<%= @user.id %>">
            <p>フォロワー：<%= link_to @user.followers.count, user_followers_path(@user) %></p>
          </div>
          <div id="dm" class="text-left mb-3">
            <% unless @user.id == current_user.id %>
              <% if (current_user.following?(@user)) && (@user.following?(current_user) ) %>
                <% if @is_room == true %>
                  <%= link_to "DMを送る", room_path(@room_id), class: "btn btn-primary"%>
                <% else %>
                  <%= form_with model: @room do |f| %>
                    <%= fields_for @entry do |e| %>
                      <%= e.hidden_field :user_id, value: @user.id %>
                    <% end %>
                    <%= f.submit "DMを始める", class: "btn btn-primary" %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-6 mx-auto pt-5">
    <h3 class="text-center border-bottom border-dark mt-5"><%= @user.name %>さんの投稿一覧</h3>
  </div>

  <% @post_images.each do |post_image| %>
    <div class="card w-25 mx-auto mt-4 shadow-lg">
      <%= link_to post_image_path(post_image.id) do %>
        <%= image_tag post_image.get_image(200,200), class:"card-img-top"; %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= image_tag post_image.user.get_profile_image(50,50), class:"mt-3 rounded-circle"; %>
          </div>
          <div class="col-10">
            <p class="card-title">
              <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
                <strong><i class="far fa-flag"></i><span> <%= post_image.name %></span></strong>
              <% end %>
            </p>
            <p class="card-text">説明：<%= post_image.caption %></p>
            <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
            <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="d-flex justify-content-center">
    <div class="mt-5"><%= paginate @post_images %></div>
  </div>
</div>