config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  resources :post_images do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :user, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get 'user/:id/mypage' => 'user#mypage', as: "mypage"
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  validates :user_id, uniqueness: {scope: :post_image_id}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  validates :name, presence: true
  validates :image, presence: true


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    else
      image.variant(resize_to_limit: [width, height]).processed
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/read_count.rb
class ReadCount < ApplicationRecord

  belongs_to :user
  belongs_to :post_image

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

 # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed
  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  # 指定したユーザーをフォロー
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/man.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.order(created_at: :desc).page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
    unless ReadCount.find_by(user_id: current_user.id, post_image_id: @post_image.id)
      current_user.read_counts.create(post_image_id: @post_image.id)
    end
  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    post_image = PostImage.find(params[:id])
    post_image.update(post_image_params)
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:name, :image, :caption)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def create
    @room = Room.create(user_id: current_user.id)
    @current_entry = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @another_entry = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to rooms_path(@room)
  end
  
  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      # roomで相手の名前を表示するために記述
      @my_user_id = current_user.id
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def mypage
    @user = current_user
    @post_images = @user.post_images.page(params[:page])
  end

  def index
    @users = User.all
    @my_user = User.find_by(id: current_user)
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id then
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      if @is_room
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/post_images/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post_image.errors.count %>件のエラーが発生しました
            </h6>
            <% @post_image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post_image, id: "post" do |f| %>
          <div class="image">
            <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          </div>
          <div id="image" class="p-3 mx-auto"></div>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :name, class:"form-control", placeholder:"タイトル" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/index.html.erb
<div class="card-list-container py-5">
  <% @post_images.each do |post_image| %>
  <div class="card w-25 mx-auto mt-4 shadow-lg">
    <%= link_to post_image_path(post_image.id) do %>
      <%= image_tag post_image.get_image(200,200), class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= image_tag post_image.user.get_profile_image(30,30), class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p><i class="fas fa-user"></i> <%= post_image.user.name %></p>
          <p class="card-title">
              <strong><i class="far fa-flag"></i><span> <%= post_image.name %></span></strong>
          </p>
          <p class="card-text"><%= post_image.caption %></p>
          <div class="d-flex justify-content-between">
            <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
            <span>❤️<%= post_image.favorites.count %> いいね</span>
            <span></span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <div class="d-flex justify-content-center">
    <div class="mt-5"><%= paginate @post_images %></div>
  </div>
</div>

app/views/post_images/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post_image.errors.count %>件のエラーが発生しました
            </h6>
            <% @post_image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post_image, id: "post" do |f| %>
          <div class="image">
            <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          </div>
          <div id="image" class="p-3 mx-auto"></div>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :name, class:"form-control", placeholder:"タイトル" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="card-list-container py-5">
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= image_tag @post_image.get_image(300,300), class:"card-img-top"; %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= link_to user_path(@post_image.user) do %>
            <%= image_tag @post_image.user.get_profile_image(80,80), class:"mt-3 rounded-circle"; %>
          <% end %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <strong><i class="fa-regular fa-flag"></i><span> <%= @post_image.name %></span></strong>
          </p>
          <p class="card-text"><%= @post_image.caption %></p>
          <p class="card-text"><%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
          <p class="card-text mt-5" id="comment_count"><%= render "post_comments/count", post_image: @post_image %></p>
          <p class="card-text" id="favorites_btn_<%= @post_image.id %>">
            <%= render "favorites/favorites", post_image: @post_image %>
          </p>
          <p class="text-right">閲覧数：<%= @post_image.read_counts.count %></p>
        </div>
        <% if @post_image.user == current_user %>
          <%= link_to "編集", edit_post_image_path(@post_image), class: "btn btn-success" %>
          <div class="ml-auto">
            <%= link_to "削除", post_image_path(@post_image), method: :delete, class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div id="comment_index">
  <%= render "post_comments/index", post_image: @post_image %>
</div>
<div class="row no-gutters mb-5">
  <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
    <h5 class="bg-dark text-white p-4 mb-0 text-center">コメント</h5>
    <div class="form-body p-3">
      <%= render "post_comments/form", post_image: @post_image, post_comment: @post_comment %>
    </div>
  </div>
</div>